-- ====================================================================
-- AYURVEDA DOSHA IDENTIFICATION EXPERT SYSTEM
-- MySQL Script & Initial Knowledge Base Seed Data
-- ====================================================================

CREATE DATABASE IF NOT EXISTS ayurveda_dosha_db;
USE ayurveda_dosha_db;

-- --------------------------------------------------------------------
-- TABLE: users
-- Holds authenticated user profiles and admin markers
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(256) NOT NULL,
  age INT NOT NULL,
  gender VARCHAR(20) NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------------------
-- TABLE: questions
-- Primary expert system questions repository
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  question TEXT NOT NULL,
  category VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------------------
-- TABLE: question_options
-- Mapping options to Vata, Pitta, Kapha points
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS question_options (
  id INT AUTO_INCREMENT PRIMARY KEY,
  question_id INT NOT NULL,
  option_text TEXT NOT NULL,
  dosha_type ENUM('vata', 'pitta', 'kapha') NOT NULL,
  score_value INT NOT NULL DEFAULT 2,
  FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------------------
-- TABLE: assessments
-- Diagnosis reports generated by core expert system rules
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS assessments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  vata_score INT NOT NULL,
  pitta_score INT NOT NULL,
  kapha_score INT NOT NULL,
  dominant_dosha VARCHAR(50) NOT NULL,
  assessment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------------------
-- TABLE: recommendations
-- Wellness suggestions corresponding to each primary dosha
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS recommendations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dosha_type ENUM('Vata', 'Pitta', 'Kapha') NOT NULL UNIQUE,
  diet_eat TEXT NOT NULL,       -- JSON array or bullet strings
  diet_avoid TEXT NOT NULL,     -- JSON array or bullet strings
  exercise TEXT NOT NULL,       -- General text advice
  yoga TEXT NOT NULL,           -- Comma separated poses
  meditation TEXT NOT NULL,     -- Meditation tips
  sleep_advice TEXT NOT NULL    -- Chronobiology suggestions
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ====================================================================
-- SAMPLE DATA INSERTIONS
-- ====================================================================

-- 1. Insert Administrator User (Password hash matches "admin123" in SHA256)
INSERT INTO users (name, email, password_hash, age, gender, is_admin)
VALUES (
  'Ayurveda Admin', 
  'admin@ayurveda.org', 
  'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 
  35, 
  'Other', 
  TRUE
);

-- 2. Insert Base Questions & Option Mappings
-- Question 1: Body build
INSERT INTO questions (id, question, category) VALUES (1, 'How would you describe your general body frame?', 'Physical Characteristics');
INSERT INTO question_options (question_id, option_text, dosha_type, score_value) VALUES 
(1, 'Lean, thin, tall or short, prominent joints and bony structure', 'vata', 2),
(1, 'Medium built, compact, well-developed musculature, stable weight', 'pitta', 2),
(1, 'Large, stocky, broad frame, tends to gain weight easily', 'kapha', 2);

-- Question 2: Skin
INSERT INTO questions (id, question, category) VALUES (2, 'Describe your skin''s natural texture and appearance:', 'Physical Characteristics');
INSERT INTO question_options (question_id, option_text, dosha_type, score_value) VALUES 
(2, 'Dry, rough, cool to touch, thin, prone to cracking or ashiness', 'vata', 2),
(2, 'Warm, soft, reddish/pinkish, sensitive, prone to acne or freckles', 'pitta', 2),
(2, 'Thick, soft, smooth, oily, pale or fair, slow to wrinkle', 'kapha', 2);

-- Question 3: Appetite
INSERT INTO questions (id, question, category) VALUES (3, 'How is your typical appetite?', 'Physiological Traits');
INSERT INTO question_options (question_id, option_text, dosha_type, score_value) VALUES 
(3, 'Variable, irregular, sometimes hungry, sometimes forgetting to eat', 'vata', 2),
(3, 'Strong, intense, can''t tolerate delayed meals, sharp hunger', 'pitta', 2),
(3, 'Low but steady, can easily skip meals without discomfort', 'kapha', 2);


-- 3. Insert Base Recommendations Base
INSERT INTO recommendations (dosha_type, diet_eat, diet_avoid, exercise, yoga, meditation, sleep_advice)
VALUES (
  'Vata',
  '["Warm, cooked, and oily foods", "Sweet, sour, and salty tastes", "Ghee, sesame oil", "Root vegetables (carrots, sweet potatoes)"]',
  '["Raw salads, iced drinks, frozen food", "Dry snacks like popcorn and chips", "Excessive caffeine"]',
  '["Gentle, grounding walking and slow swimming"]',
  'Tadasana, Balasana, Virabhadrasana',
  'Grounding breath awareness for 15 minutes daily.',
  'Go to sleep early by 10:00 PM in a cozy warm environment.'
);

INSERT INTO recommendations (dosha_type, diet_eat, diet_avoid, exercise, yoga, meditation, sleep_advice)
VALUES (
  'Pitta',
  '["Cooling Basmati rice, oats, barley", "Sweet, bitter, and astringent tastes", "Melons, cucumber, sweet potatoes"]',
  '["Spicy, oily, salty, or highly acidic foods", "Chili peppers, tomatoes, garlic, vinegar", "Caffeine, alcohol"]',
  '["Cooling nature walks, swimming, and cycling"]',
  'Chandra Namaskar, Bhujangasana, Matsyasana',
  'Compassion-focused metta meditation to let go of irritation.',
  'Sleep by 10:30 PM under light breathable cotton blankets.'
);

INSERT INTO recommendations (dosha_type, diet_eat, diet_avoid, exercise, yoga, meditation, sleep_advice)
VALUES (
  'Kapha',
  '["Warm, light, dry, and highly spicy foods", "Millet, buckwheat, and barley", "Bitter leafy greens, ginger, black pepper"]',
  '["Heavy dairy products like cheese and ice cream", "Deep-fried items, fatty meats, white flour", "Excessive sugar and salt"]',
  '["HIIT workouts, heavy cardio, running, and cycling"]',
  'Dynamic Surya Namaskar, Dhanurasana, Downward Dog',
  'Active, dynamic walking or chanting meditation.',
  'Wake up early by 6:00 AM. Avoid sleeping more than 7 hours. No daytime naps.'
);
